paths:
    data_dir: /storage/projects/vinkle/ez_compass_imaging/data/monai_test_dataset
    checkpoint_dir: /storage/projects/vinkle/ez_compass_imaging/code/monai_unet_test/checkpoints
    output_dir: out

data:
    cache_rate: 1.0
    val_size: 9
    batch_size: 2
    num_workers: 4

training:
    seed: 0
    max_epochs: 600
    val_interval: 2
    roi_size: [160, 160, 160]
    sw_batch_size: 4

model:
    in_channels: 1
    out_channels: 2